version: "3.8"

services:
  local-db:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: ssafy603
      MYSQL_ROOT_PASSWORD: ssafy603
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql
  local-db-migrate:
    image: flyway/flyway:7
    restart: always
    environment:
      - FLYWAY_DB_URL=jdbc:mysql://local-db/ssafy603
      - FLYWAY_DB_USER=root
      - FLYWAY_DB_PASSWORD=ssafy603
    command: migrate
    volumes:
      - ../../db/flyway.conf:/flyway/conf/flyway.conf
      - ../../db/migration:/flyway/sql

